import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Web notification feature: the per-recipient feed (`notifications`, written by
 * the `database` channel) and browser Web Push subscriptions
 * (`web_push_subscriptions`, written by the `web-push` channel).
 *
 * Production forces `synchronize: false` and runs `migration:run` on boot (see
 * src/data-source.ts + Dockerfile), so these tables MUST come from here — the
 * manual SQL in docs/notifications-announcements-manual-migration.sql is only a
 * convenience for the pre-existing tables and is not executed by anything.
 *
 * Timestamp note: landed as …0010, then …0014, but both collided with
 * migrations develop had already claimed by the time this branch was rebased
 * (`TokenCollectionNameIdx1718900000010`, then `TransactionsBuySellIndexes
 * 1718900000014`). Renumbered to …0020 — strictly after every existing
 * migration (through …0019) — so history has one migration per timestamp and
 * TypeORM's execution order is unambiguous. Safe to renumber: this migration
 * has never run against any real environment (unmerged feature branch), so no
 * `migrations` history table anywhere records an old name.
 *
 * Written idempotently (IF NOT EXISTS) because some environments already have
 * these tables from that manual SQL or from a `DB_SYNC=true` dev boot.
 *
 * Keep in sync with:
 *   notifications/entities/notification.entity.ts
 *   notifications/entities/web-push-subscription.entity.ts
 */
export class WebNotificationFeed1718900000020 implements MigrationInterface {
  name = 'WebNotificationFeed1718900000020';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // ── per-recipient feed (source of truth for bell / unread / history) ─────
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "notifications" (
        "id"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "address"    character varying NOT NULL,
        "type"       character varying NOT NULL,
        "title"      character varying NOT NULL,
        "body"       text NOT NULL,
        "data"       jsonb NULL,
        "read_at"    timestamp NULL,
        "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
      )
    `);
    // Feed pagination + the retention per-address cap both filter by address and
    // range/order by id (WHERE address=? AND id<? ORDER BY id DESC).
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "notifications_address_id_idx"
        ON "notifications" ("address", "id")
    `);
    // Unread-count + mark-all-read scans.
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "notifications_address_read_at_idx"
        ON "notifications" ("address", "read_at")
    `);
    // Retention sweep: read rows older than the horizon (no address filter).
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "notifications_retention_idx"
        ON "notifications" ("created_at") WHERE "read_at" IS NOT NULL
    `);
    // Superseded by (address, id) — pagination orders by id, not created_at.
    await queryRunner.query(
      `DROP INDEX IF EXISTS "notifications_address_created_at_idx"`,
    );

    // ── browser Web Push subscriptions ──────────────────────────────────────
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "web_push_subscriptions" (
        "id"           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "address"      character varying NOT NULL,
        "endpoint"     text NOT NULL,
        "p256dh"       text NOT NULL,
        "auth"         text NOT NULL,
        "user_agent"   character varying NULL,
        "last_seen_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        "created_at"   timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        "updated_at"   timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
      )
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "web_push_subscriptions_address_idx"
        ON "web_push_subscriptions" ("address")
    `);
    // Natural key: a browser re-subscribing yields the same endpoint, so the
    // upsert (ON CONFLICT (endpoint)) re-points it to the proven address.
    await queryRunner.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS "web_push_subscriptions_endpoint_uq"
        ON "web_push_subscriptions" ("endpoint")
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS "web_push_subscriptions"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "notifications"`);
  }
}
