-- Manual migration: push-notifications + announcements subsystem.
--
-- WHY THIS EXISTS: production runs with `synchronize` forced OFF (see
-- src/configs/database.ts — `DB_SYNC=true` is ignored when NODE_ENV=production),
-- so new entities are NOT auto-created in prod. These tables back
-- src/notifications/** and src/announcements/**. Apply this once per
-- environment before enabling the feature. Idempotent — safe to re-run.
--
--   psql "$DATABASE_URL" -f docs/notifications-announcements-manual-migration.sql
--
-- Keep in sync with the entities:
--   notifications/entities/device-token.entity.ts
--   notifications/entities/device-challenge.entity.ts
--   notifications/entities/notification-preference.entity.ts
--   announcements/entities/announcement.entity.ts
--   announcements/entities/announcement-target.entity.ts
-- and with agent/admin/tasks/announcements/02-data-model.md.

BEGIN;

-- ── notifications: device tokens ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS device_tokens (
  expo_push_token character varying PRIMARY KEY,
  address         character varying NOT NULL,
  platform        character varying NULL,
  app_version     character varying NULL,
  device_id       character varying NULL,
  last_seen_at    timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_at      timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at      timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);
CREATE INDEX IF NOT EXISTS device_tokens_address_idx
  ON device_tokens (address);
CREATE INDEX IF NOT EXISTS device_tokens_last_seen_at_idx
  ON device_tokens (last_seen_at);

-- ── notifications: signed device-link challenges ────────────────────────────
CREATE TABLE IF NOT EXISTS notification_device_challenges (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nonce       character varying NOT NULL,
  address     character varying NOT NULL,
  expires_at  timestamp NOT NULL,
  consumed_at timestamp NULL,
  created_at  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);
CREATE UNIQUE INDEX IF NOT EXISTS notification_device_challenges_nonce_uq
  ON notification_device_challenges (nonce);
CREATE INDEX IF NOT EXISTS notification_device_challenges_address_idx
  ON notification_device_challenges (address);

-- ── notifications: per-(address,type) opt-out flags ─────────────────────────
CREATE TABLE IF NOT EXISTS notification_preferences (
  address    character varying NOT NULL,
  type       character varying NOT NULL,
  enabled    boolean NOT NULL DEFAULT true,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (address, type)
);

-- ── announcements ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS announcements (
  id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title            character varying NOT NULL,
  description      text NOT NULL,
  scheduled_at     timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  target_type      character varying NOT NULL DEFAULT 'all',
  feed_visible     boolean NOT NULL DEFAULT true,
  claimed_at       timestamp NULL,
  claim_token      character varying NULL,
  attempt_count    integer NOT NULL DEFAULT 0,
  processed_at     timestamp NULL,
  recipient_count  integer NULL,
  delivered_count  integer NULL,
  opted_out_count  integer NULL,
  no_channel_count integer NULL,
  failed_count     integer NULL,
  error            text NULL,
  created_by       character varying NULL,
  created_at       timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at       timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);
CREATE INDEX IF NOT EXISTS announcements_scheduled_at_idx
  ON announcements (scheduled_at);
CREATE INDEX IF NOT EXISTS announcements_claimed_at_idx
  ON announcements (claimed_at);
CREATE INDEX IF NOT EXISTS announcements_processed_at_idx
  ON announcements (processed_at);

-- ── announcement_targets (recipient list for target_type='specific') ────────
CREATE TABLE IF NOT EXISTS announcement_targets (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  announcement_id integer NOT NULL,
  address         character varying NOT NULL
);
CREATE INDEX IF NOT EXISTS announcement_targets_announcement_id_idx
  ON announcement_targets (announcement_id);
CREATE INDEX IF NOT EXISTS announcement_targets_address_idx
  ON announcement_targets (address);
CREATE UNIQUE INDEX IF NOT EXISTS uq_announcement_targets
  ON announcement_targets (announcement_id, address);

COMMIT;
