-- Manual migration: X posting-reward subsystem.
--
-- WHY THIS EXISTS: production runs with `synchronize` forced OFF (see
-- src/configs/database.ts — `DB_SYNC=true` is ignored when NODE_ENV=production),
-- so the reward entities are NOT auto-created in prod. Apply this once per
-- environment BEFORE enabling any PROFILE_X_*_REWARD_ENABLED flag. Idempotent —
-- safe to re-run.
--
--   psql "$DATABASE_URL" -f docs/profile-x-rewards-manual-migration.sql
--
-- CRITICAL: the UNIQUE / partial-unique indexes below are not cosmetic — they
-- are the load-bearing double-spend / double-ledger guards. The service relies
-- on `ON CONFLICT DO NOTHING` (`.orIgnore()`) against them. If a table is
-- created WITHOUT its unique index, the same tweet / streak-day can be paid
-- multiple times. Do not drop or weaken them.
--
-- Keep in sync with the entities:
--   profile/entities/profile-x-posting-reward.entity.ts
--   profile/entities/profile-x-post-reward-ledger.entity.ts
--   profile/entities/profile-x-streak-bonus-reward.entity.ts
-- and with the service src/profile/services/profile-x-posting-reward.service.ts
-- (isXIdentityUniqueConstraintError / isReferralCodeUniqueConstraintError match
-- the index names ux_profile_x_posting_rewards_x_user_id / *_referral_code).

BEGIN;

-- ── aggregate per-address reward row ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS profile_x_posting_rewards (
  address                 character varying PRIMARY KEY,
  x_username              character varying NULL,
  x_user_id               character varying NULL,
  rewarded_x_user_id      character varying NULL,
  qualified_posts_count   integer NOT NULL DEFAULT 0,
  referral_code           character varying NULL,
  last_x_api_scan_at      timestamp NULL,
  follower_count          integer NULL,
  follower_tier_index     integer NULL,
  follower_snapshot_at    timestamp NULL,
  last_qualifying_post_day date NULL,
  current_streak_days     integer NOT NULL DEFAULT 0,
  x_lookup_failure_count  integer NOT NULL DEFAULT 0,
  verified_at             timestamp NULL,
  last_scanned_tweet_id   character varying NULL,
  tx_hash                 character varying NULL,
  status                  character varying NOT NULL DEFAULT 'pending',
  error                   text NULL,
  retry_count             integer NOT NULL DEFAULT 0,
  next_retry_at           timestamp NULL,
  last_attempt_at         timestamp NULL,
  created_at              timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at              timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

-- Added after the table's first release: the X identity an address became bound
-- to on its first qualifying post, so a re-link to a different handle cannot farm
-- per-post/streak rewards again. ADD COLUMN IF NOT EXISTS keeps this idempotent
-- for tables created before this column existed.
ALTER TABLE profile_x_posting_rewards
  ADD COLUMN IF NOT EXISTS rewarded_x_user_id character varying NULL;

-- One reward row per X identity (anti-sybil) and per referral code. Partial so
-- many rows may legitimately have NULL x_user_id / referral_code.
CREATE UNIQUE INDEX IF NOT EXISTS ux_profile_x_posting_rewards_x_user_id
  ON profile_x_posting_rewards (x_user_id)
  WHERE x_user_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_profile_x_posting_rewards_referral_code
  ON profile_x_posting_rewards (referral_code)
  WHERE referral_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS profile_x_posting_rewards_x_username_idx
  ON profile_x_posting_rewards (x_username);
CREATE INDEX IF NOT EXISTS profile_x_posting_rewards_x_user_id_idx
  ON profile_x_posting_rewards (x_user_id);
CREATE INDEX IF NOT EXISTS profile_x_posting_rewards_tx_hash_idx
  ON profile_x_posting_rewards (tx_hash);

-- ── per-post reward ledger ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS profile_x_post_reward_ledger (
  id                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  address               character varying NOT NULL,
  x_user_id             character varying NOT NULL,
  tweet_id              character varying NOT NULL,
  tweet_created_at      timestamp NULL,
  tweet_utc_day         date NULL,
  reward_kind           character varying NOT NULL DEFAULT 'per_post',
  amount_aettos         character varying NULL,
  follower_count_at_post integer NULL,
  tier_index_at_post    integer NULL,
  tx_hash               character varying NULL,
  status                character varying NOT NULL DEFAULT 'pending',
  error                 text NULL,
  retry_count           integer NOT NULL DEFAULT 0,
  next_retry_at         timestamp NULL,
  created_at            timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at            timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

-- Each tweet rewarded at most once; at most one rewarded post per identity/day.
CREATE UNIQUE INDEX IF NOT EXISTS ux_profile_x_post_reward_ledger_identity
  ON profile_x_post_reward_ledger (x_user_id, tweet_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_profile_x_post_reward_ledger_day
  ON profile_x_post_reward_ledger (x_user_id, tweet_utc_day)
  WHERE tweet_utc_day IS NOT NULL;
CREATE INDEX IF NOT EXISTS profile_x_post_reward_ledger_address_idx
  ON profile_x_post_reward_ledger (address);
CREATE INDEX IF NOT EXISTS profile_x_post_reward_ledger_x_user_id_idx
  ON profile_x_post_reward_ledger (x_user_id);
CREATE INDEX IF NOT EXISTS profile_x_post_reward_ledger_tweet_id_idx
  ON profile_x_post_reward_ledger (tweet_id);
CREATE INDEX IF NOT EXISTS profile_x_post_reward_ledger_tx_hash_idx
  ON profile_x_post_reward_ledger (tx_hash);

-- ── recurring streak-bonus completions ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS profile_x_streak_bonus_rewards (
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  address              character varying NOT NULL,
  x_user_id            character varying NOT NULL,
  streak_length        integer NOT NULL DEFAULT 10,
  streak_completed_day date NOT NULL,
  amount_aettos        character varying NULL,
  tx_hash              character varying NULL,
  status               character varying NOT NULL DEFAULT 'pending',
  error                text NULL,
  retry_count          integer NOT NULL DEFAULT 0,
  next_retry_at        timestamp NULL,
  created_at           timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at           timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

-- Each streak completion (identity + day) recorded and paid at most once.
CREATE UNIQUE INDEX IF NOT EXISTS ux_profile_x_streak_bonus_completion
  ON profile_x_streak_bonus_rewards (x_user_id, streak_completed_day);
CREATE INDEX IF NOT EXISTS profile_x_streak_bonus_rewards_address_idx
  ON profile_x_streak_bonus_rewards (address);
CREATE INDEX IF NOT EXISTS profile_x_streak_bonus_rewards_x_user_id_idx
  ON profile_x_streak_bonus_rewards (x_user_id);
CREATE INDEX IF NOT EXISTS profile_x_streak_bonus_rewards_tx_hash_idx
  ON profile_x_streak_bonus_rewards (tx_hash);

COMMIT;
