BEGIN;

DO $$
BEGIN
  CREATE TYPE profile_chain_name_claims_status_enum AS ENUM (
    'pending',
    'preclaimed',
    'claimed',
    'completed',
    'failed'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

CREATE TABLE IF NOT EXISTS profile_chain_name_challenges (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nonce character varying NOT NULL,
  address character varying NOT NULL,
  expires_at timestamp NOT NULL,
  consumed_at timestamp NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

CREATE UNIQUE INDEX IF NOT EXISTS profile_chain_name_challenges_nonce_uq
  ON profile_chain_name_challenges (nonce);
CREATE INDEX IF NOT EXISTS profile_chain_name_challenges_address_idx
  ON profile_chain_name_challenges (address);

CREATE TABLE IF NOT EXISTS profile_chain_name_claims (
  address character varying PRIMARY KEY,
  name character varying NOT NULL,
  status profile_chain_name_claims_status_enum NOT NULL DEFAULT 'pending',
  salt text NULL,
  preclaim_height integer NULL,
  preclaim_tx_hash character varying NULL,
  claim_tx_hash character varying NULL,
  update_tx_hash character varying NULL,
  transfer_tx_hash character varying NULL,
  error text NULL,
  retry_count integer NOT NULL DEFAULT 0,
  next_retry_at timestamp NULL,
  last_attempt_at timestamp NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

CREATE UNIQUE INDEX IF NOT EXISTS profile_chain_name_claims_name_uq
  ON profile_chain_name_claims (name);
CREATE INDEX IF NOT EXISTS profile_chain_name_claims_preclaim_tx_hash_idx
  ON profile_chain_name_claims (preclaim_tx_hash);
CREATE INDEX IF NOT EXISTS profile_chain_name_claims_claim_tx_hash_idx
  ON profile_chain_name_claims (claim_tx_hash);
CREATE INDEX IF NOT EXISTS profile_chain_name_claims_update_tx_hash_idx
  ON profile_chain_name_claims (update_tx_hash);
CREATE INDEX IF NOT EXISTS profile_chain_name_claims_transfer_tx_hash_idx
  ON profile_chain_name_claims (transfer_tx_hash);

COMMIT;
