BEGIN;

DO $$
BEGIN
  CREATE TYPE profile_x_verification_rewards_status_enum AS ENUM (
    'pending',
    'paid',
    'failed'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

ALTER TYPE profile_x_verification_rewards_status_enum
  ADD VALUE IF NOT EXISTS 'ineligible_followers';
ALTER TYPE profile_x_verification_rewards_status_enum
  ADD VALUE IF NOT EXISTS 'blocked_username_conflict';

DO $$
BEGIN
  CREATE TYPE profile_x_invite_challenges_purpose_enum AS ENUM (
    'create',
    'bind'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE profile_x_invites_status_enum AS ENUM (
    'active',
    'bound'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE profile_x_invite_milestone_rewards_status_enum AS ENUM (
    'pending',
    'paid',
    'failed'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

ALTER TABLE profile_x_verification_rewards
  ADD COLUMN IF NOT EXISTS retry_count integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS next_retry_at timestamp NULL,
  ADD COLUMN IF NOT EXISTS last_attempt_at timestamp NULL;

CREATE TABLE IF NOT EXISTS profile_x_invite_challenges (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nonce character varying NOT NULL,
  address character varying NOT NULL,
  purpose profile_x_invite_challenges_purpose_enum NOT NULL,
  invite_code character varying NULL,
  expires_at timestamp NOT NULL,
  consumed_at timestamp NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

CREATE UNIQUE INDEX IF NOT EXISTS profile_x_invite_challenges_nonce_uq
  ON profile_x_invite_challenges (nonce);
CREATE INDEX IF NOT EXISTS profile_x_invite_challenges_address_idx
  ON profile_x_invite_challenges (address);
CREATE INDEX IF NOT EXISTS profile_x_invite_challenges_invite_code_idx
  ON profile_x_invite_challenges (invite_code);

CREATE TABLE IF NOT EXISTS profile_x_invites (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inviter_address character varying NOT NULL,
  invitee_address character varying NULL,
  code character varying NOT NULL,
  status profile_x_invites_status_enum NOT NULL DEFAULT 'active',
  bound_at timestamp NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

CREATE UNIQUE INDEX IF NOT EXISTS profile_x_invites_code_uq
  ON profile_x_invites (code);
CREATE UNIQUE INDEX IF NOT EXISTS profile_x_invites_invitee_address_uq
  ON profile_x_invites (invitee_address);
CREATE INDEX IF NOT EXISTS profile_x_invites_inviter_address_idx
  ON profile_x_invites (inviter_address);

CREATE TABLE IF NOT EXISTS profile_x_invite_credits (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inviter_address character varying NOT NULL,
  invitee_address character varying NOT NULL,
  invite_code character varying NOT NULL,
  verified_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

CREATE UNIQUE INDEX IF NOT EXISTS profile_x_invite_credits_inviter_invitee_uq
  ON profile_x_invite_credits (inviter_address, invitee_address);
CREATE UNIQUE INDEX IF NOT EXISTS profile_x_invite_credits_invitee_uq
  ON profile_x_invite_credits (invitee_address);
CREATE INDEX IF NOT EXISTS profile_x_invite_credits_inviter_address_idx
  ON profile_x_invite_credits (inviter_address);
CREATE INDEX IF NOT EXISTS profile_x_invite_credits_invite_code_idx
  ON profile_x_invite_credits (invite_code);

CREATE TABLE IF NOT EXISTS profile_x_invite_milestone_rewards (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inviter_address character varying NOT NULL,
  threshold integer NOT NULL DEFAULT 10,
  tx_hash character varying NULL,
  status profile_x_invite_milestone_rewards_status_enum NOT NULL DEFAULT 'pending',
  error text NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

CREATE UNIQUE INDEX IF NOT EXISTS profile_x_invite_milestone_rewards_inviter_threshold_uq
  ON profile_x_invite_milestone_rewards (inviter_address, threshold);
CREATE INDEX IF NOT EXISTS profile_x_invite_milestone_rewards_inviter_address_idx
  ON profile_x_invite_milestone_rewards (inviter_address);
CREATE INDEX IF NOT EXISTS profile_x_invite_milestone_rewards_tx_hash_idx
  ON profile_x_invite_milestone_rewards (tx_hash);

COMMIT;
