name: Develop deploy (multi-server)
on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "Version to deploy to develop"
        default: "develop"
        required: false
        type: string
  workflow_call:
    inputs:
      VERSION:
        description: "Version to deploy to develop"
        default: "develop"
        required: false
        type: string
jobs:
  deploy:
    name: Deploy develop (${{ matrix.server_name }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - server_name: "wordcraftfun"
            deploy_host: "api.dev.wordcraft.fun"
            deploy_key: "${{ secrets.DEV_DEPLOY_KEY }}"
          - server_name: "trendminerfun"
            deploy_host: "api.dev.trendminer.fun"
            deploy_key: "${{ secrets.DEV_TRENDMINERFUN_DEPLOY_KEY }}"
    uses: ./.github/workflows/ssh_deploy.yaml
    with:
      VERSION: ${{ inputs.VERSION }}
      CONTAINER_NAME: "develop-${{ matrix.server_name }}-api"
    secrets:
      AE_NETWORK_ID: "ae_mainnet"
      API_HOST_PORT: "3043"
      DB_DATABASE: "api"
      DEPLOY_HOST: ${{ matrix.deploy_host }}
      DEPLOY_KEY: ${{ matrix.deploy_key }}
      DEPLOY_USERNAME: ${{ secrets.DEV_DEPLOY_USERNAME }}
      DB_USER: ${{ secrets.DEV_DB_USER }}
      DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}
