name: Develop deploy (uat+mainnet)
on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "Version to deploy to develop"
        default: "develop"
        required: false
        type: string
      CONTAINER_NAME:
        description: "Container name prefix (network suffix will be appended)"
        default: "develop-wordcraftfun-api"
        required: false
        type: string
  workflow_call:
    inputs:
      VERSION:
        description: "Version to deploy to develop"
        default: "develop"
        required: false
        type: string
      CONTAINER_NAME:
        description: "Container name prefix (network suffix will be appended)"
        default: "develop-wordcraftfun-api"
        required: false
        type: string
jobs:
  call_deploy_uat:
    name: Deploy develop (uat)
    uses: ./.github/workflows/ssh_deploy.yaml
    with:
      VERSION: ${{ inputs.VERSION }}
      CONTAINER_NAME: "${{ inputs.CONTAINER_NAME }}-testnet"
    secrets:
      AE_NETWORK_ID: "ae_uat"
      API_HOST_PORT: "3040"
      DB_DATABASE: "api"
      DEPLOY_HOST: "${{ secrets.DEV_DEPLOY_HOST }}"
      DEPLOY_USERNAME: "${{ secrets.DEV_DEPLOY_USERNAME }}"
      DEPLOY_KEY: "${{ secrets.DEV_DEPLOY_KEY }}"
      DB_USER: "${{ secrets.DEV_DB_USER }}"
      DB_PASSWORD: "${{ secrets.DEV_DB_PASSWORD }}"
  call_deploy_mainnet:
    name: Deploy develop (mainnet)
    uses: ./.github/workflows/ssh_deploy.yaml
    with:
      VERSION: ${{ inputs.VERSION }}
      CONTAINER_NAME: "${{ inputs.CONTAINER_NAME }}-mainnet"
    secrets:
      AE_NETWORK_ID: "ae_mainnet"
      API_HOST_PORT: "3043"
      DB_DATABASE: "api"
      DEPLOY_HOST: "${{ secrets.DEV_DEPLOY_HOST }}"
      DEPLOY_USERNAME: "${{ secrets.DEV_DEPLOY_USERNAME }}"
      DEPLOY_KEY: "${{ secrets.DEV_DEPLOY_KEY }}"
      DB_USER: "${{ secrets.DEV_DB_USER }}"
      DB_PASSWORD: "${{ secrets.DEV_DB_PASSWORD }}"
