name: Production deploy (uat+mainnet)
on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "Version to deploy to production"
        default: "latest"
        required: false
        type: string
      CONTAINER_NAME:
        description: "Container name prefix (network suffix will be appended)"
        default: "production-wordcraftfun-api"
        required: false
        type: string
  workflow_call:
    inputs:
      VERSION:
        description: "Version to deploy to production"
        default: "main"
        required: false
        type: string
      CONTAINER_NAME:
        description: "Container name prefix (network suffix will be appended)"
        default: "production-wordcraftfun-api"
        required: false
        type: string
jobs:
  call_deploy_uat:
    name: Deploy production (uat)
    uses: ./.github/workflows/ssh_deploy.yaml
    with:
      VERSION: ${{ inputs.VERSION }}
      CONTAINER_NAME: "${{ inputs.CONTAINER_NAME }}-testnet"
    secrets:
      AE_NETWORK_ID: "ae_uat"
      API_HOST_PORT: "3030"
      DB_DATABASE: "api"
      DEPLOY_HOST: "${{ secrets.PROD_DEPLOY_HOST }}"
      DEPLOY_USERNAME: "${{ secrets.PROD_DEPLOY_USERNAME }}"
      DEPLOY_KEY: "${{ secrets.PROD_DEPLOY_KEY }}"
      DB_USER: "${{ secrets.PROD_DB_USER }}"
      DB_PASSWORD: "${{ secrets.PROD_DB_PASSWORD }}"
  call_deploy_mainnet:
    name: Deploy production (mainnet)
    uses: ./.github/workflows/ssh_deploy.yaml
    with:
      VERSION: ${{ inputs.VERSION }}
      CONTAINER_NAME: "${{ inputs.CONTAINER_NAME }}-mainnet"
    secrets:
      AE_NETWORK_ID: "ae_mainnet"
      API_HOST_PORT: "3033"
      DB_DATABASE: "api"
      DEPLOY_HOST: "${{ secrets.PROD_DEPLOY_HOST }}"
      DEPLOY_USERNAME: "${{ secrets.PROD_DEPLOY_USERNAME }}"
      DEPLOY_KEY: "${{ secrets.PROD_DEPLOY_KEY }}"
      DB_USER: "${{ secrets.PROD_DB_USER }}"
      DB_PASSWORD: "${{ secrets.PROD_DB_PASSWORD }}"
