# This workflow is only for inclusion in other workflows.
name: Deploy via ssh
on:
  workflow_call:
    inputs:
      VERSION:
        description: "Version to deploy (dockerhub tag)"
        required: false
        default: "latest"
        type: string
      CONTAINER_NAME:
        description: "Container name"
        default: "wordcraftfun-api"
        required: false
        type: string
    secrets:
      DEPLOY_HOST:
        description: "Host to deploy to"
        required: true
      DEPLOY_USERNAME:
        description: "Username to use for ssh"
        required: true
      DEPLOY_KEY:
        description: "SSH key to use for ssh"
        required: true
      AE_NETWORK_ID:
        description: "Aeternity network id (ae_uat, ae_mainnet)"
        required: false
      API_HOST_PORT:
        description: "Host port to expose the API on (3000)"
        required: true
      DB_USER:
        description: "Database user"
        required: true
      DB_PASSWORD:
        description: "Database password"
        required: true
      DB_DATABASE:
        description: "Database name"
        required: true
jobs:
  deploy:
    name: Deploy via ssh
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy script
        uses: appleboy/ssh-action@v1.0.0
        env:
          VERSION: "${{ inputs.VERSION }}"
          SHA: "${{ github.sha }}"
          AE_NETWORK_ID: "${{ secrets.AE_NETWORK_ID }}"
          HOST_DATA_DIR: "./${{ inputs.CONTAINER_NAME }}"
          API_HOST_PORT: "${{ secrets.API_HOST_PORT }}"
          DB_USER: "${{ secrets.DB_USER }}"
          DB_PASSWORD: "${{ secrets.DB_PASSWORD }}"
          DB_DATABASE: "${{ secrets.DB_DATABASE }}"
        with:
          host: "${{ secrets.DEPLOY_HOST }}"
          username: "${{ secrets.DEPLOY_USERNAME }}"
          key: "${{ secrets.DEPLOY_KEY }}"
          envs: >
            AE_NETWORK_ID,
            DB_USER,
            DB_PASSWORD,
            API_HOST_PORT,
            HOST_DATA_DIR,
            SHA
          script: |
            echo $SHA > $HOST_DATA_DIR/REVISION || true
            docker pull "superherodotcom/wordcraftfun-api:${{ inputs.VERSION }}" || true
            docker stop ${{ inputs.CONTAINER_NAME }} || true
            docker rm ${{ inputs.CONTAINER_NAME }} || true
            docker run -d --name ${{ inputs.CONTAINER_NAME }} \
              --restart=always \
              -p ${{ secrets.API_HOST_PORT }}:3000 \
              -e APP_PORT="3000" \
              -e DB_USER \
              -e DB_PASSWORD \
              -e AE_NETWORK_ID \
              -e DB_DATABASE \
              -e NODE_ENV=production \
              -e REDIS_HOST=${{ inputs.CONTAINER_NAME }}-redis \
              -e REDIS_PORT=6379 \
              -e DB_TYPE=postgres \
              -e DB_HOST=${{ inputs.CONTAINER_NAME }}-db \
              -e DB_PORT=5432 \
              -e DB_SYNC=true \
              --network ${{ inputs.CONTAINER_NAME }}-db \
              superherodotcom/wordcraftfun-api:${{ inputs.VERSION }}
